spring:
  datasource:
    hikari:
      jdbcUrl: jdbc:oracle:thin:@localhost:1522:XE
      username: USR_INSPECCIONES
      password: inspeccion123
      driver-class-name: oracle.jdbc.driver.OracleDriver
      maximum-pool-size: 5
      minimum-idle: 1
      connection-test-query: SELECT 1 FROM DUAL

  flyway:
    enabled: false

server:
  port: 8083

services:
  territorial:
    url: http://localhost:8082

security:
  jwt:
    secret: dev-secret-key-solo-para-desarrollo-local-32chars

logging:
  level:
    inspeccion: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
