-- init-oracle.sql
-- Script de inicializacion para Oracle 10g
-- Ejecutar como SYSDBA o usuario con privilegios DBA

-- Crear usuario de base de datos
CREATE USER inspeccion_user IDENTIFIED BY inspeccion_pass
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

-- Otorgar privilegios necesarios
GRANT CONNECT TO inspeccion_user;
GRANT RESOURCE TO inspeccion_user;
GRANT CREATE SESSION TO inspeccion_user;
GRANT CREATE TABLE TO inspeccion_user;
GRANT CREATE SEQUENCE TO inspeccion_user;
GRANT CREATE VIEW TO inspeccion_user;
GRANT CREATE INDEX TO inspeccion_user;
GRANT UNLIMITED TABLESPACE TO inspeccion_user;

-- Vista para reporte de resumen de inspecciones
CREATE OR REPLACE VIEW V_RESUMEN_INSPECCIONES AS
SELECT
    i.ID_INSPECCION,
    i.NUMERO_INSPECCION,
    i.FECHA_INSPECCION,
    i.TIPO_INSPECCION,
    i.ESTADO,
    i.ID_LOTE,
    i.NOMBRE_INSPECTOR,
    COUNT(DISTINCT di.ID_DETALLE) AS TOTAL_DETALLES,
    COUNT(DISTINCT dp.ID_DETALLE_PLAGA) AS TOTAL_PLAGAS,
    NVL(MAX(dp.NIVEL_INCIDENCIA), 0) AS MAX_INCIDENCIA,
    NVL(AVG(dp.NIVEL_INCIDENCIA), 0) AS PROM_INCIDENCIA
FROM INSPECCION_FITOSANITARIA i
LEFT JOIN DETALLE_INSPECCION di ON i.ID_INSPECCION = di.ID_INSPECCION
LEFT JOIN DETALLE_PLAGA dp ON di.ID_DETALLE = dp.ID_DETALLE
GROUP BY
    i.ID_INSPECCION, i.NUMERO_INSPECCION, i.FECHA_INSPECCION,
    i.TIPO_INSPECCION, i.ESTADO, i.ID_LOTE, i.NOMBRE_INSPECTOR;

COMMIT;
