-- V1__create_inspeccion.sql
-- Tabla principal de inspecciones fitosanitarias - Oracle 10g compatible

CREATE SEQUENCE SEQ_INSPECCION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE INSPECCION_FITOSANITARIA (
    ID_INSPECCION       NUMBER(19)      NOT NULL,
    NUMERO_INSPECCION   VARCHAR2(50)    NOT NULL,
    FECHA_INSPECCION    DATE            NOT NULL,
    TIPO_INSPECCION     VARCHAR2(20)    NOT NULL,
    ESTADO              VARCHAR2(30)    NOT NULL,
    ID_LOTE             NUMBER(19)      NOT NULL,
    CODIGO_LOTE         VARCHAR2(50),
    NOMBRE_INSPECTOR    VARCHAR2(200)   NOT NULL,
    CEDULA_INSPECTOR    VARCHAR2(20)    NOT NULL,
    OBSERVACIONES       VARCHAR2(2000),
    FECHA_CREACION      TIMESTAMP       NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP       NOT NULL,
    CONSTRAINT PK_INSPECCION PRIMARY KEY (ID_INSPECCION),
    CONSTRAINT UQ_NUMERO_INSPECCION UNIQUE (NUMERO_INSPECCION),
    CONSTRAINT CHK_TIPO_INSPECCION CHECK (TIPO_INSPECCION IN ('RUTINARIA','EMERGENCIA','SEGUIMIENTO','CUARENTENA')),
    CONSTRAINT CHK_ESTADO_INSPECCION CHECK (ESTADO IN ('PROGRAMADA','EN_PROCESO','COMPLETADA','CANCELADA','PENDIENTE_REVISION'))
);

CREATE INDEX IDX_INSP_ESTADO ON INSPECCION_FITOSANITARIA(ESTADO);
CREATE INDEX IDX_INSP_LOTE ON INSPECCION_FITOSANITARIA(ID_LOTE);
CREATE INDEX IDX_INSP_INSPECTOR ON INSPECCION_FITOSANITARIA(CEDULA_INSPECTOR);
CREATE INDEX IDX_INSP_FECHA ON INSPECCION_FITOSANITARIA(FECHA_INSPECCION);
