-- V2__create_detalle_inspeccion.sql
-- Tabla de detalles de inspección por cultivo - Oracle 10g compatible

CREATE SEQUENCE SEQ_DETALLE_INSPECCION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE DETALLE_INSPECCION (
    ID_DETALLE          NUMBER(19)      NOT NULL,
    ID_INSPECCION       NUMBER(19)      NOT NULL,
    NOMBRE_CULTIVO      VARCHAR2(200)   NOT NULL,
    AREA_INSPECCIONADA  NUMBER(10,2)    NOT NULL,
    TOTAL_PLANTAS       NUMBER(10)      DEFAULT 0,
    PLANTAS_MUESTREADAS NUMBER(10)      DEFAULT 0,
    RESULTADO           VARCHAR2(500),
    OBSERVACIONES       VARCHAR2(2000),
    FECHA_CREACION      TIMESTAMP       NOT NULL,
    CONSTRAINT PK_DETALLE_INSPECCION PRIMARY KEY (ID_DETALLE),
    CONSTRAINT FK_DETALLE_INSPECCION FOREIGN KEY (ID_INSPECCION)
        REFERENCES INSPECCION_FITOSANITARIA(ID_INSPECCION),
    CONSTRAINT CHK_AREA_POSITIVA CHECK (AREA_INSPECCIONADA > 0),
    CONSTRAINT CHK_PLANTAS_POSITIVAS CHECK (TOTAL_PLANTAS >= 0),
    CONSTRAINT CHK_MUESTREADAS CHECK (PLANTAS_MUESTREADAS >= 0)
);

CREATE INDEX IDX_DETALLE_INSP ON DETALLE_INSPECCION(ID_INSPECCION);
