-- V3__create_detalle_plaga.sql
-- Tabla de detalle de plagas detectadas - Oracle 10g compatible

CREATE SEQUENCE SEQ_DETALLE_PLAGA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE DETALLE_PLAGA (
    ID_DETALLE_PLAGA    NUMBER(19)      NOT NULL,
    ID_DETALLE          NUMBER(19)      NOT NULL,
    NOMBRE_PLAGA        VARCHAR2(200)   NOT NULL,
    NOMBRE_CIENTIFICO   VARCHAR2(300),
    PLANTAS_AFECTADAS   NUMBER(10)      DEFAULT 0,
    NIVEL_INCIDENCIA    NUMBER(5,2)     DEFAULT 0,
    NIVEL_SEVERIDAD     VARCHAR2(20),
    AREA_AFECTADA       NUMBER(10,2)    DEFAULT 0,
    ACCION_RECOMENDADA  VARCHAR2(1000),
    FECHA_DETECCION     DATE,
    CONSTRAINT PK_DETALLE_PLAGA PRIMARY KEY (ID_DETALLE_PLAGA),
    CONSTRAINT FK_PLAGA_DETALLE FOREIGN KEY (ID_DETALLE)
        REFERENCES DETALLE_INSPECCION(ID_DETALLE),
    CONSTRAINT CHK_SEVERIDAD CHECK (NIVEL_SEVERIDAD IN ('BAJO','MEDIO','ALTO','CUARENTENA','NO_DETERMINADO') OR NIVEL_SEVERIDAD IS NULL),
    CONSTRAINT CHK_INCIDENCIA CHECK (NIVEL_INCIDENCIA >= 0 AND NIVEL_INCIDENCIA <= 100)
);

CREATE INDEX IDX_PLAGA_DETALLE ON DETALLE_PLAGA(ID_DETALLE);
CREATE INDEX IDX_PLAGA_INCIDENCIA ON DETALLE_PLAGA(NIVEL_INCIDENCIA);
CREATE INDEX IDX_PLAGA_FECHA ON DETALLE_PLAGA(FECHA_DETECCION);
